/*****************************************************************************
|*  Copyright		:	(c) 2003 CAS
|*  Version		:	0.1
|*  Modified		:	2004/08/20
****************************************************************************/
#define LABEL_CAP_STRUCT_SIZE	32

#define	LABCAP_ID_TOTAL	0
#define	LABCAP_ID_UNIT_PRICE_WEIGHT	1
#define	LABCAP_ID_UNIT_PRICE_CNT	2
#define	LABCAP_ID_UNIT_PRICE_PCS	3
#define	LABCAP_ID_WEIGHT	4
#define	LABCAP_ID_QUANTITY	5
#define	LABCAP_ID_TARE	6
#define	LABCAP_ID_DISC_PRICE	7
#define	LABCAP_ID_REG_PRICE	8
#define	LABCAP_ID_TAX_PRICE	9
#define	LABCAP_ID_PACKEDDATE	10
#define	LABCAP_ID_SELLBYDATE	11
#define	LABCAP_ID_COOKBYDATE	12
#define	LABCAP_ID_PRODUCEDDATE	13
#define	LABCAP_ID_PACKEDTIME	14
#define	LABCAP_ID_SELLBYTIME	15
#define	LABCAP_ID_PAYMENT	16
#define	LABCAP_ID_CHANGE	17
#define	LABCAP_ID_NET_WEIGHT	18
#define	LABCAP_ID_GROSS_WEIGHT	19
#define	LABCAP_ID_MAN_WEIGHT	20
#define	LABCAP_ID_PERCENT_TARE	21
#define	LABCAP_ID_PERCENT_TARE_LIMIT	22
#define	LABCAP_ID_TTL_TOTAL_PRICE	23
#define	LABCAP_ID_TTL_TOTAL_COUNT	24
#define	LABCAP_ID_TTL_TOTAL_TAX	25
#define	LABCAP_ID_REFERENCE	26
#define	LABCAP_ID_BORN_IN	27
#define	LABCAP_ID_BRED_IN	28
#define	LABCAP_ID_SLAUGHT_IN	29
#define	LABCAP_ID_CUT_IN	30
#define	LABCAP_ID_TOTAL_REPACK	31
#define	LABCAP_ID_TTL_VOID_COUNT	32
#define	LABCAP_ID_TTL_VOID_PRICE	33
#define	LABCAP_ID_TTL_TOTAL_WEIGHT	34
#define	LABCAP_ID_TTL_TOTAL_QUANTITY	35
#define	LABCAP_ID_INGREDIENT	36
#define	LABCAP_ID_PLU_NO	37
#define	LABCAP_ID_ORIGIN	38





		
#define	LABCAP_ID_TXT_1KG	40
#define	LABCAP_ID_TXT_100G	41
#define	LABCAP_ID_TXT_1LB	42
#define	LABCAP_ID_TXT_1_2LB	43
#define	LABCAP_ID_TXT_1_4LB	44
#define	LABCAP_ID_TXT_TITLE_TOTAL	45
#define	LABCAP_ID_TXT_TITLE_GTOTAL	46
#ifdef USE_WEIGHT_UNIT_500G
#define LABCAP_ID_TXT_500G	47	//china
#endif





#define RCPTCAP_BASE	50

#define RCPTCAP_ID_LST_PLULIST      1	// PT001
#define RCPTCAP_ID_LST_PARAMETER_LIST 2	// PT002
#define RCPTCAP_ID_LST_START_NO     3	// PT003
#define RCPTCAP_ID_LST_END_NO       4
#define RCPTCAP_ID_LST_NO           5
#define RCPTCAP_ID_LST_FORMAT       6
#define RCPTCAP_ID_LST_LEVEL        7
#define RCPTCAP_ID_LST_NAME         8
#define RCPTCAP_ID_LST_TYPE         9
#define RCPTCAP_ID_LST_UNITPRICE 10
#define RCPTCAP_ID_LST_ADDRESS      11
#define RCPTCAP_ID_LST_TEL          12
#define RCPTCAP_ID_LST_CREDIT_LMT   13
#define RCPTCAP_ID_LST_SPEED_KEY    14
#define RCPTCAP_ID_LST_PLU_NO       15
#define RCPTCAP_ID_LST_TEXT         16
#define RCPTCAP_ID_LST_TARE_WEIGHT  17
#define RCPTCAP_ID_LST_TARE_TYPE    18
#define RCPTCAP_ID_LST_TAX_RATE     19
#define RCPTCAP_ID_LST_TAX_TYPE     20
#define RCPTCAP_ID_LST_BORN_IN      21
#define RCPTCAP_ID_LST_BRED_IN      22
#define RCPTCAP_ID_LST_SLAUGHTER    23
#define RCPTCAP_ID_LST_CUTTED_IN    24
#define RCPTCAP_ID_LST_COUNTRY_NO   25
#define RCPTCAP_ID_LST_DEPT_NO      26
#define RCPTCAP_ID_LST_PRIMARY_SIGN 27
#define RCPTCAP_ID_LST_LAST_SIGN 28
#define RCPTCAP_ID_LST_DECIMAL_POINT 29
#define RCPTCAP_ID_LST_PRICE_FORMAT 30
#define RCPTCAP_ID_LST_ITEM_CODE 31
#define RCPTCAP_ID_LST_QUANTITY 32
#define RCPTCAP_ID_COM_MISC_WEIGHT      51
#define RCPTCAP_ID_COM_MISC_COUNT       52
#define RCPTCAP_ID_COM_MISC_PCS  53
#define RCPTCAP_ID_COM_INT_TAX          54
#define RCPTCAP_ID_COM_EXT_TAX          55
#define RCPTCAP_ID_COM_NOT_AVAILABLE 56
#define RCPTCAP_ID_COM_PAY_CASH 57
#define RCPTCAP_ID_COM_PAY_PIN_CHIP 58
#define RCPTCAP_ID_COM_PAY_CHECK 59
#define RCPTCAP_ID_COM_PAY_CREDIT_CARD 60
#define RCPTCAP_ID_COM_PAY_CREDIT_NODE 61
#define RCPTCAP_ID_COM_PAY_COUPON 62
#define RCPTCAP_ID_COM_PAY_BONUS_POINT 63
#define RCPTCAP_ID_COM_PAY_CREDIT_SALES 64
// CJK080215
#define RCPTCAP_ID_DSP_TITLE_TARE 65
#define RCPTCAP_ID_DSP_TITLE_WEIGHT 66
#define RCPTCAP_ID_DSP_TITLE_QTY 67
#define RCPTCAP_ID_DSP_TITLE_PCS 68
#define RCPTCAP_ID_DSP_TITLE_UNITPRICE 69
#define RCPTCAP_ID_DSP_TITLE_TOTALPRICE 70
//////////////
#define RCPTCAP_ID_REP_TITLE_PLU    71
#define RCPTCAP_ID_REP_TITLE_MISC   72
#define RCPTCAP_ID_REP_TITLE_GROUP  73
#define RCPTCAP_ID_REP_TITLE_DEPT   74
#define RCPTCAP_ID_REP_TITLE_SCALE  75
#define RCPTCAP_ID_REP_TITLE_HOUR   76
#define RCPTCAP_ID_REP_TITLE_CLERK  77
#define RCPTCAP_ID_REP_LAST_RESET   78
#define RCPTCAP_ID_REP_DEPT_NO      79
#define RCPTCAP_ID_REP_PLU_NO       80
#define RCPTCAP_ID_REP_GROUP_NO     81
#define RCPTCAP_ID_REP_SCALE_NO     82
#define RCPTCAP_ID_REP_HOUR_NO      83
#define RCPTCAP_ID_REP_CLERK_NO     84
#define RCPTCAP_ID_REP_GRAND_TOTAL 85
#define RCPTCAP_ID_REP_GRAND_COUNT 86
#define RCPTCAP_ID_REP_GRAND_PRICE 87
#define RCPTCAP_ID_REP_ROUNDED_TOTAL 88
#define RCPTCAP_ID_REP_SUBTOTAL 89
#define RCPTCAP_ID_REP_TRAN_COUNT 90
#define RCPTCAP_ID_REP_PRICE 91
#define RCPTCAP_ID_REP_WEIGHT 92
#define RCPTCAP_ID_REP_QUANTITY 93
#define RCPTCAP_ID_REP_TAX_PRICE 94
#define RCPTCAP_ID_REP_ROUNDED_SUBTOTAL 95
#define RCPTCAP_ID_REP_GRAND_SCALE_TOTAL 96
#define RCPTCAP_ID_REP_PREPACK_COUNT 97
#define RCPTCAP_ID_REP_RETURN_COUNT 98
#define RCPTCAP_ID_REP_VOID_COUNT 99
#define RCPTCAP_ID_REP_REPACK_COUNT 100
#define RCPTCAP_ID_REP_OVERRIDE_COUNT 101
#define RCPTCAP_ID_REP_DISCOUNT_COUNT 102
#define RCPTCAP_ID_REP_NOSALEOPEN_COUNT 103
#define RCPTCAP_ID_REP_NEGATIVE_COUNT 104
#define RCPTCAP_ID_REP_TAX_SUMMARY 105
#define RCPTCAP_ID_REP_PAY_SUMMARY 106
#define RCPTCAP_ID_REP_NON_GROUP 107
#define RCPTCAP_ID_REP_COUNT_LABEL 108
#define RCPTCAP_ID_REP_COUNT_LABEL_VOL 109
#define RCPTCAP_ID_REP_PREPACK_VOL 110
#define RCPTCAP_ID_REP_PREPACK_WEIGHT 111
#define RCPTCAP_ID_REP_SUBTOTAL_SUMMARY 112
#define RCPTCAP_ID_REP_SALE_SUMMARY 113
#define RCPTCAP_ID_REP_PAY 114
#define RCPTCAP_ID_REP_NO_PAY 115
#define RCPTCAP_ID_REP_PAY_SUBTOTAL 116
#define RCPTCAP_ID_TKT_TOTAL 121
#define RCPTCAP_ID_TKT_ROUNDED_TOTAL         122
#define RCPTCAP_ID_TKT_SUBTOTAL         123
#define RCPTCAP_ID_TKT_VOID 124
#define RCPTCAP_ID_TKT_ARTICLES         125
#define RCPTCAP_ID_TKT_PAYMENT 126
#define RCPTCAP_ID_TKT_CHANGE           127
#define RCPTCAP_ID_TKT_TAX_INFO 128
#define RCPTCAP_ID_TKT_TAX_TOTAL 129
#define RCPTCAP_ID_TKT_NICKNAME         130
#define RCPTCAP_ID_TKT_CUSTOM_NAME 131
#define RCPTCAP_ID_TKT_CUSTOMER 132
#define RCPTCAP_ID_TKT_AUTOGRAPH 133
#define RCPTCAP_ID_TKT_TRACEABILITY 134
#define RCPTCAP_ID_TKT_BORN_COUNTRY 135
#define RCPTCAP_ID_TKT_BRED_COUNTRY 136
#define RCPTCAP_ID_TKT_SLA_HOUSE 137
#define RCPTCAP_ID_TKT_SLA_COUNTRY 138
#define RCPTCAP_ID_TKT_CUT_HALL 139
#define RCPTCAP_ID_TKT_CUT_COUNTRY 140
#define RCPTCAP_ID_TKT_TOTAL_REPACK 141
#define RCPTCAP_ID_TKT_SAVED_PRICE 142
#define RCPTCAP_ID_TKT_TRAINING 143		//insert by se-hyung for training clerk 20070627
#define RCPTCAP_ID_TKT_YOU_PAY 144		//Added by JJANG 20080104
#define RCPTCAP_ID_REP_TAX_NET_AMOUNT	145
#define RCPTCAP_ID_REP_TAX_GROSS_AMOUNT	146
#define RCPTCAP_ID_REP_TAX_AMOUNT	147
#define RCPTCAP_ID_REP_TAX_GRAND_TOTAL	148
#define RCPTCAP_ID_TKT_ROUND_DIFFERENCE 149



//extern void label_caption_init(void);
//extern void label_caption_save(INT16U id,char *str);
extern INT8U label_caption_read(INT16U id,char *str);
extern INT8U label_caption_get_string(INT16U id, char *str, INT8U currency_order);
//extern void receipt_caption_init(void);
//extern void receipt_caption_save(INT16U id, char *str);
extern INT8U receipt_caption_read(INT16U id, char *str);

